### ISSUE TITLE
Compile for Nuke 10 (on Windows 10)

### ISSUE THREAD

**Issue by chuckleberri** [julik/sylens#25]
Excellent tools thank you very much.  Is there a chance we will see an update compiled for Nuke 10 any time soon?

**Comment by julik** [comment]
It might be possible but I can't give any guarantees. As a matter of fact I don't have a good Nuke build pipeline on any OS at the moment.

**Comment by mhirabayashi** [comment]
Thank you for sharing this tool.

https://github.com/mhirabayashi/sylens/tree/master/plugins-64
Add compiled binaries for Nuke 10.0, 10.5, 11.0 on Windows.

**Comment by Degraund** [comment]
Can you for Linux, Nuke 10 lay out SyLens.so?

**Comment by la0011** [comment]
> 
> 
> Thank you for sharing this tool.
> 
> https://github.com/mhirabayashi/sylens/tree/builds-311-win/plugins-64
> Add compiled binaries for Nuke 10.0, 10.5, 11.0 on Windows.

Hi  mhirabayashi ,

do you think you could add win10 binaries for Nuke11.3v2?

Thanks

**Comment by mhirabayashi** [comment]
@la0011 Here it is.
https://github.com/mhirabayashi/sylens/tree/builds-311-win/plugins-64/win-11.3

**Comment by la0011** [comment]
Thank you  mhirabayashi !

**Comment by julik** [comment]
🙏 Many thanks @mhirabayashi I will integrate them in the source tree

**Comment by julik** [comment]
Will close this issue, please reopen should a new Nuke version come around
